apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "app.example.com/v1alpha1",
          "kind": "AppService",
          "metadata": {
            "name": "example-appservice"
          },
          "spec": {
            "size": 3
          }
        }
      ]
    capabilities: Basic Install
  name: operatordemo.v
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AppService is the Schema for the appservices API
      kind: AppService
      name: appservices.app.example.com
      version: v1alpha1
  displayName: Operatordemo
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments:
      - name: operatordemo
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: operatordemo
          strategy: {}
          template:
            metadata:
              labels:
                name: operatordemo
            spec:
              containers:
              - command:
                - operatordemo
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: operatordemo
                image: REPLACE_IMAGE
                imagePullPolicy: Always
                name: operatordemo
                resources: {}
              serviceAccountName: operatordemo
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - operatordemo
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - app.example.com
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: operatordemo
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ""
  maintainers:
  - {}
  maturity: alpha
  provider: {}
  version: 0.0.0
