apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexeyproject
spec:
  replicas: 1
  selector:
    matchLabels:
      name: alexeyproject
  template:
    metadata:
      labels:
        name: alexeyproject
    spec:
      serviceAccountName: alexeyproject
      containers:
        - name: alexeyproject
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - alexeyproject
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "alexeyproject"
