apiVersion: apps/v1
kind: Deployment
metadata:
  name: operatordemo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: operatordemo
  template:
    metadata:
      labels:
        name: operatordemo
    spec:
      serviceAccountName: operatordemo
      containers:
        - name: operatordemo
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - operatordemo
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "operatordemo"
