kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: alexeyproject
subjects:
- kind: ServiceAccount
  name: alexeyproject
roleRef:
  kind: Role
  name: alexeyproject
  apiGroup: rbac.authorization.k8s.io
