kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operatordemo
subjects:
- kind: ServiceAccount
  name: operatordemo
roleRef:
  kind: Role
  name: operatordemo
  apiGroup: rbac.authorization.k8s.io
